root = "."
testdata_dir = "testdata"
tmp_dir = "out"

[build]
args_bin = []
bin = "./out/liber"
cmd = "mage dev:build"
delay = 1000
exclude_dir = ["web/dist"]
exclude_file = []
exclude_regex = ["_test.go", "_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = ["cmd", "internal", "handlers", "middleware", "services", "views", "web"]
include_ext = ["go", "templ", "css", "js"]
include_file = []
kill_delay = 1000
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = ["lsof -i :8081 -sTCP:LISTEN -t | xargs -r kill -9"]
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[proxy]
enabled = true
proxy_port = 8082
app_port = 8081

[color]
app = "blue"
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
keep_scroll = true
