linters:
  disable-all: true
  enable:
    - containedctx
    - errcheck
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - whitespace