default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.60.1
    hooks:
      - id: golangci-lint
  - repo: local
    hooks:
      - id: commitlint
        stages: [commit-msg]
        name: commitlint
        description: Commitlint hook
        language: node
        entry: yarn commitlint --edit
        pass_filenames: false
        always_run: true