default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: go tool -modfile=tools/go.mod golangci-lint run --new-from-rev HEAD --fix
        types: [go]
        language: golang
        require_serial: true
        pass_filenames: false
      - id: commitlint
        stages: [commit-msg]
        name: commitlint
        description: Commitlint hook
        language: node
        entry: yarn commitlint --edit
        pass_filenames: false
        always_run: true
      - id: templ
        name: templ
        description: Verifies that generated templ files are up-to-date
        entry: templ generate
        files: '.*\.templ'
        language: golang
        pass_filenames: false