default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: go tool -modfile=tools/go.mod golangci-lint run --new-from-rev HEAD --fix
        types: [go]
        language: golang
        require_serial: true
        pass_filenames: false
      - id: commitlint
        stages: [commit-msg]
        name: commitlint
        description: Commitlint hook
        language: node
        entry: pnpm commitlint --edit
        pass_filenames: false
        always_run: true
      - id: fmt
        name: fmt
        description: Verifies that files are formatted correctly
        entry: task fmt
        files: \.(go|templ)$
        language: golang
        pass_filenames: false
      - id: generate
        name: generate
        description: Verifies that generated files are up-to-date
        entry: go generate ./...
        pass_filenames: false
        language: golang
        always_run: true