version: '3'

vars:
  MODULE:
    sh: go list -m
  BUILD_BIN: out/liber

tasks:
  generate:
    desc: Generate necessary files for building the binary
    cmd: go generate ./...

  build:
    desc: Build liber binary
    deps:
      - generate
    vars:
      CSS_BUNDLE:
        sh: basename web/dist/bundle-*.css
      JS_BUNDLE:
        sh: basename web/dist/bundle-*.js
      LDFLAGS:
        - "-X '{{joinPath .MODULE \"web\"}}.CssBundle={{.CSS_BUNDLE}}'"
        - "-X '{{joinPath .MODULE \"web\"}}.JsBundle={{.JS_BUNDLE}}'"
    cmd: go build -ldflags="{{.LDFLAGS | join " "}}" -o {{ .BUILD_BIN }} {{ .MODULE }}/cmd/liber

  lint:
    desc: Lint project code
    cmd: go tool -modfile=tools/go.mod golangci-lint run

  fmt:
    desc: Format project code
    cmds:
      - go tool -modfile=tools/go.mod golangci-lint fmt
      - go tool -modfile=tools/go.mod templ fmt .

  run:
    desc: Run a local development server
    cmd: go tool -modfile=tools/go.mod air --build.bin {{ .BUILD_BIN }} server --log-level=DEBUG
