version: '3'

vars:
  MODULE:
    sh: go list -m
  BUILD_BIN: out/liber

tasks:
  build:
    desc: Build liber binary
    deps:
      - assets
      - templ
    cmds:
      - go build -o {{ .BUILD_BIN }} {{ .MODULE }}/cmd/liber

  lint:
    desc: Lint project code
    cmds:
      - go tool -modfile=tools/go.mod golangci-lint run

  fmt:
    desc: Format project code
    cmds:
      - go tool -modfile=tools/go.mod golangci-lint fmt

  run:
    desc: Run a local development server
    cmds:
      - go tool -modfile=tools/go.mod air --build.bin {{ .BUILD_BIN }} server --dev

  assets:
    cmds:
      - pnpm rollup --config --silent
    internal: true
    sources:
      - web/src/**/*.js
      - web/src/**/*.css
      - web/src/**/*.scss
    generates:
      - web/dist/bundle.min.js
      - web/dist/bundle.min.css


  templ:
    cmds:
      - go tool -modfile=tools/go.mod templ generate
    internal: true
